# example netlify.toml
[build]
  base = "utsavsamiti/"
  publish = "utsavsamiti/public"
  command = "hugo --gc --themesDir ../.. --config config-prod.toml"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.101.0"
  HUGO_THEME = "Massively"
