name = "Utsava Samiti"
license = "Creative Commons"
licenselink = "https://github.com/shanmukh15/sahabhavanautsavasamiti/blob/master/LICENSE"
description = "An elegant open-source and mobile-first theme"
homepage = "https://html5up.net/uploads/demos/massively/index.html"
tags = ["utsav", "sahabhavana"]
features = ["webpage"]
min_version = "0.101.0"

[author]
    name = "Shanmukha rao G"
    repo = "https://github.com/shanmukh15/sahabhavanautsavasamiti.git"

# If porting an existing theme
[original]
    author = "Curtis Timson"
    homepage = "https://curtiscode.dev/"
    repo = "https://html5up.net/massively"